export { ALL_MODULES } from './lib/modules';
export { TERMINOLOGY } from './terminology';
export { PATCHES, applyPatches } from './patches/index';
export type { PatchFn } from './patches/index';
export { NARRATION, getBlockNarration } from './narration.generated';
export { TERRAIN_COLORS, GERMAN_POS_COLORS, TERRAIN_PALETTE_EXTRA } from './lib/terrain-palette';
export { SYMBOLOGY } from './lib/symbology';
export type { SimbologiaRenderAs, SimbologiaEntry, SimbologiaCategory } from './lib/symbology';
export { SETUP_GUIDE } from './lib/setup-guide';
export type { SetupStep, SetupStepGroup } from './lib/setup-guide';
export { HISTORY } from './lib/history';
export type { HistoriaBlock, HistoriaSection } from './lib/history';
