// GENERATED by tools/tts/extract-narration.mjs — do not edit by hand.

/**
 * Maps each narratable block key ("<lessonId>#<blockIndex>") to its
 * pre-generated MP3 asset path relative to the app root.
 */
export const NARRATION: Record<string, string> = {
  "lesson-1-1#0": "assets/audio/ae549e2e3789.mp3",
  "lesson-1-1#1": "assets/audio/a9a98e865538.mp3",
  "lesson-1-1#2": "assets/audio/c548caeb335c.mp3",
  "lesson-1-1#3": "assets/audio/04d91079d65e.mp3",
  "lesson-1-1#4": "assets/audio/3ef0065dc0e9.mp3",
  "lesson-1-2#0": "assets/audio/5d2025076c9e.mp3",
  "lesson-1-2#1": "assets/audio/4a9829d8e65a.mp3",
  "lesson-1-2#3": "assets/audio/beb5c4b392a0.mp3",
  "lesson-1-2#4": "assets/audio/17b4824141ec.mp3",
  "lesson-1-2#5": "assets/audio/4f346c02d1a9.mp3",
  "lesson-1-2#7": "assets/audio/89abdb6f399d.mp3",
  "lesson-1-2#8": "assets/audio/fdf4d51fce74.mp3",
  "lesson-1-2#9": "assets/audio/1798b93b02bf.mp3",
  "lesson-1-2#11": "assets/audio/96464f22544b.mp3",
  "lesson-1-3#0": "assets/audio/023387c07028.mp3",
  "lesson-1-3#1": "assets/audio/a7797eb455c7.mp3",
  "lesson-1-3#2": "assets/audio/6e50c7d69f3a.mp3",
  "lesson-1-3#3": "assets/audio/65c05d51451d.mp3",
  "lesson-1-3#4": "assets/audio/4520b1d075dc.mp3",
  "lesson-1-3#5": "assets/audio/bf816598c330.mp3",
  "lesson-4-1#0": "assets/audio/d1374d69f748.mp3",
  "lesson-4-1#1": "assets/audio/b1baac240b14.mp3",
  "lesson-4-1#2": "assets/audio/14acc4a2d6a7.mp3",
  "lesson-4-1#3": "assets/audio/16b6f91b1509.mp3",
  "lesson-4-1#4": "assets/audio/59be2fbe8c4c.mp3",
  "lesson-4-1#5": "assets/audio/d10f739efe46.mp3",
  "lesson-4-1#6": "assets/audio/592a08c1c5a2.mp3",
};

/**
 * Returns the audio asset path for a given lesson block, or undefined if
 * the block is non-narratable or no audio has been generated for it.
 *
 * @param lessonId  - the lesson id (e.g. "lesson-1-1")
 * @param blockIndex - the zero-based index into lesson.blocks
 */
export function getBlockNarration(lessonId: string, blockIndex: number): string | undefined {
  return NARRATION[`${lessonId}#${blockIndex}`];
}
