// GENERATED by tools/tts/extract-narration.mjs — do not edit by hand.

/**
 * Maps each narratable block key ("<lessonId>#<blockIndex>") to its
 * pre-generated MP3 asset path relative to the app root.
 */
export const NARRATION: Record<string, string> = {
  "lesson-1-1#0": "assets/audio/a9b2e180d7f0.mp3",
  "lesson-1-1#1": "assets/audio/a9a98e865538.mp3",
  "lesson-1-1#2": "assets/audio/a028ab58f29a.mp3",
  "lesson-1-1#3": "assets/audio/04d91079d65e.mp3",
  "lesson-1-1#4": "assets/audio/85a595eee6d7.mp3",
  "lesson-1-2#0": "assets/audio/5d2025076c9e.mp3",
  "lesson-1-2#1": "assets/audio/bf9053755347.mp3",
  "lesson-1-2#3": "assets/audio/a838ae62435a.mp3",
  "lesson-1-2#4": "assets/audio/ec7fd8440747.mp3",
  "lesson-1-2#5": "assets/audio/79821a4e1298.mp3",
  "lesson-1-2#7": "assets/audio/ef7564370d97.mp3",
  "lesson-1-2#8": "assets/audio/f91aa21c354e.mp3",
  "lesson-1-2#9": "assets/audio/1798b93b02bf.mp3",
  "lesson-1-2#11": "assets/audio/0faf632eb766.mp3",
  "lesson-1-3#0": "assets/audio/0ebff830a5e4.mp3",
  "lesson-1-3#1": "assets/audio/da0032f589fe.mp3",
  "lesson-1-3#2": "assets/audio/b1cae88cf05c.mp3",
  "lesson-1-3#3": "assets/audio/82201ca218ec.mp3",
  "lesson-1-3#4": "assets/audio/4520b1d075dc.mp3",
  "lesson-1-3#5": "assets/audio/7d9caf36c00f.mp3",
  "lesson-4-1#0": "assets/audio/d1374d69f748.mp3",
  "lesson-4-1#1": "assets/audio/602e21af623b.mp3",
  "lesson-4-1#2": "assets/audio/14acc4a2d6a7.mp3",
  "lesson-4-1#3": "assets/audio/a54d0bc00b50.mp3",
  "lesson-4-1#4": "assets/audio/3bc810d8b713.mp3",
  "lesson-4-1#5": "assets/audio/5e0e61ec6266.mp3",
  "lesson-4-1#6": "assets/audio/592a08c1c5a2.mp3",
};

/**
 * Returns the audio asset path for a given lesson block, or undefined if
 * the block is non-narratable or no audio has been generated for it.
 *
 * @param lessonId  - the lesson id (e.g. "lesson-1-1")
 * @param blockIndex - the zero-based index into lesson.blocks
 */
export function getBlockNarration(lessonId: string, blockIndex: number): string | undefined {
  return NARRATION[`${lessonId}#${blockIndex}`];
}
